version: '3'
services:
  
  backend:
    container_name: java_container1
    image: crqyuee/oa_test1:${BUILD_ID} 
    ports:
      - 7333:6333
#    depends_on:
#      - db
  
#  frontend:
#    image: your-frontend-image:${BUILD_ID}
#    ports:
#      - 80:80
# 啊手动阀手动阀第三方和v计划v就
#  db:
#    image: your-mysql-image
#    environment:
#      MYSQL_ROOT_PASSWORD: your-password
#    volumes:
#      - db-data:/var/lib/mysql

#volumes:
#  db-data:
